### PR TITLE
Assume stringsAsFactors=FALSE

### PR DESCRIPTION
**Pull request by MichaelChirico**
Another follow-up to #2603

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Where relevant, maybe we can also get rid of them from tests?

image

**Comment by IndrajeetPatil** [comment]
Even this one?

```r  
    exp <- data.frame(
    filename = rep("dummy.R", 2L),
    line_number = c(1L, 2L),
    column_number = c(1L, 6L),
    type = c("style", "error"),
    message = c("", "Under no circumstances is the use of foobar allowed."),
    line = c("", "a <- 1"),
    linter = c(NA_character_, NA_character_), # These are assigned in lint() now.
    stringsAsFactors = FALSE
  )
```

**Comment by MichaelChirico** [comment]
must have missed one :)

**Comment by MichaelChirico** [comment]
OK, ran an _ad hoc_ linter this time to make sure everything's covered:

```r
l <- make_linter_from_xpath(lint_message = "", "
  //SYMBOL_SUB[text() = 'stringsAsFactors']
    /parent::expr[not(
      expr/SYMBOL_FUNCTION_CALL[text() = 'expand.grid']
      or ./expr/expr/SYMBOL_FUNCTION_CALL[text() = 'table']
    )]
  ")
lint_package(linters = l())
```

**Review by IndrajeetPatil — APPROVED** [review]
Thanks!

**Pull request merged**
