### PR TITLE
refactor commas_linter to XPath

### PR DESCRIPTION
**Pull request by AshesITR**
Part of #1186

### CODE REVIEW

**Comment by AshesITR** [comment]
Crazy how much code can be saved by XPath 😮

**Comment by MichaelChirico** [comment]
glorious xpath 🙌🙌🙌

**Review by MichaelChirico — APPROVED** [review]
any need to mess with the source markers here?

**Comment by AshesITR** [comment]
Yes, could be done as a follow-up, similar to `spaces_inside_linter`.
Currently, all lints mark the comma, which is fine for spaces before, but useless for spaces after.

**Pull request merged**
