### PR TITLE
Bump roxygen2 version

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Re-documenting with the new version of `{roxygen2}` (7.3.0) seems to generate a non-parsable `NAMESPACE` file.

I am wondering if this is a bug upstream.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
cc @hadley is this an {roxygen2} regression? Here's the markup leading to this garbled output:

https://github.com/r-lib/lintr/blob/bad1632f23b77f41cec13fb6f1c883302f64f506/R/lintr-package.R#L20-L24

**Comment by MichaelChirico** [comment]
`git bisect` points to https://github.com/r-lib/roxygen2/commit/1ea43c9237e9d10bdf70ae023956396862f87d3c as the culprit

**Comment by AshesITR** [comment]
@MichaelChirico thanks for the pointer. I looked at the diff and found the problem:

`update_namespace_imports()` sorts the lines, which will break any multi-line `@rawNamespace` directive.

**Comment by MichaelChirico** [comment]
> update_namespace_imports

Thanks for the pointer; filed something that works in https://github.com/r-lib/roxygen2/pull/1573.

**Comment by IndrajeetPatil** [comment]
Thank you, both, for getting to the bottom of this so quickly and for filing a fix!

**Comment by IndrajeetPatil** [comment]
Can confirm that devel-roxygen2 fixes the issue. 

The new warning in the examples looks legit, though, and something we should deal with.

**Comment by MichaelChirico** [comment]
> The new warning in the examples looks legit, though, and something we should deal with.

Can you point to the warning? I'm seeing various issues & can't figure out what's the problem, exactly. Maybe we're seeing something different, though.

**Comment by IndrajeetPatil** [comment]
I see:

```r
> ### Name: get_r_string
> ### Title: Extract text from 'STR_CONST' nodes
> ### Aliases: get_r_string
> 
> ### ** Examples
> 
> ## Don't show: 
> if (requireNamespace("withr", quietly = TRUE)) (if (getRversion() >= "3.4") withAutoprint else force)({ # examplesIf
+ ## End(Don't show)
+ tmp <- withr::local_tempfile(lines = "c('a', 'b')")
+ expr_as_xml <- get_source_expressions(tmp)$expressions[[1L]]$xml_parsed_content
+ writeLines(as.character(expr_as_xml))
+ get_r_string(expr_as_xml, "expr[2]") # "a"
+ get_r_string(expr_as_xml, "expr[3]") # "b"
+ 
+ # more importantly, extract strings under R>=4 raw strings
+ ## Don't show: 
+ }) # examplesIf
> tmp <- withr::local_tempfile(lines = "c('a', 'b')")
> expr_as_xml <- get_source_expressions(tmp)$expressions[[1L]]$xml_parsed_content
Error in file(con, "r") : 
  (converted from warning) cannot open file '/var/folders/xr/v_vddzvs33q5wg7jv9mr__4h0000gn/T//Rtmpk8Dcx3/file640749057d03': No such file or directory
Run `rlang::last_trace()` to see where the error occurred.
ℹ Loading lintr
> rlang::last_trace()
<error/rlang_error>
Error:
! No such file or directory
---
Backtrace:
     ▆
  1. └─devtools::run_examples(run_donttest = TRUE, run_dontrun = TRUE)
  2.   └─base::lapply(...)
  3.     └─pkgload (local) FUN(X[[i]], ...)
  4.       └─base::source(tmp, echo = !quiet, local = env, max.deparse.length = Inf)
  5.         ├─base::withVisible(eval(ei, envir))
  6.         └─base::eval(ei, envir)
  7.           └─base::eval(ei, envir)
  8.             ├─(if (getRversion() >= "3.4") withAutoprint else force)(...) at /Rtmpk8Dcx3/file6407739f7efc.R:8:1
  9.             │ └─base::source(...)
 10.             │   ├─base::withVisible(eval(ei, envir))
 11.             │   └─base::eval(ei, envir)
 12.             │     └─base::eval(ei, envir)
 13.             └─lintr::get_source_expressions(tmp)
 14.               └─lintr:::read_lines(filename) at lintr/R/get_source_expressions.R:69:5
 15.                 ├─base::withCallingHandlers(...) at lintr/R/utils.R:182:3
 16.                 └─base::readLines(file, warn = TRUE, ...)
 17.                   └─base::file(con, "r")
```

**Comment by MichaelChirico** [comment]
Hmm I'm not seeing that. Maybe transient. Closing + reopening to see if 7.3.1 gets picked up by CI yet.

**Comment by MichaelChirico** [comment]
#2518 proves (IINM) the issue is not related to {roxygen2}, since running with {pkgload} skips the `document=TRUE` step {devtools} does.

The new error might then be related to the {pkgload} update. Anyway, merging this.

**Review by MichaelChirico — APPROVED** [review]

**Comment by IndrajeetPatil** [comment]
No longer relevant after #2519 merge

**Pull request closed without merging**
