### PR TITLE
Missing package symbol

### LINKED ISSUE #1037: False positive in missing_package_linter for symbol
```
lintr::lint("loadNamespace(package)\n", lintr::missing_package_linter())
```

lints:

```
<text>:1:1: warning: Package 'package' is not installed.
loadNamespace(package)
^~~~~~~~~~~~~~~~~~~~~~
```

As seen in our own code:

https://github.com/r-lib/lintr/blob/36236c3c030e64f4a74fb8468d72e8f68b1defbd/R/with.R#L112

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #1037

### CODE REVIEW

**Comment by AshesITR** [comment]
Do you also want to add the `character.only` skip I added to `unused_import_linter()`, for the same reason?

**Comment by MichaelChirico** [comment]
sure... i must be missing something though :grimacing: 

```
grep -Fr "character.only" R
grep -Fr "unused_import_linter" R
```

both turn up empty...

**Comment by MichaelChirico** [comment]
Ah, #239

**Comment by MichaelChirico** [comment]
handled `character.only`

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
