### PR TITLE
add a test to ensure inst/lintr/linters.csv is up to date

### PR DESCRIPTION
**Pull request by MichaelChirico**
Part of #916

This has been the biggest pain point thus far -- making sure to remember the .csv is in sync as we make edits/rename things. Having this test will at least make it so we fail early.

Renamed the only two `_linter` objects in our namespace that aren't linters; thankfully neither is exported so we don't have to worry much.

### CODE REVIEW

**Comment by AshesITR** [comment]
I used `getNamespaceExports()` instead of `ls()`, which didn't return the factories and makes sure that the available linters are actually exported. WDYT?

I think it's still fine to rename the two function factories.

**Comment by MichaelChirico** [comment]
my intent was to make sure the linters are exported but you're right this test doesn't do that, how about a separate test for that?

**Comment by AshesITR** [comment]
I'm not sure if tests already see the new `getNamespaceExports()` when a new linter is added, but I'd say we should definitely add a test for that if we check this.

Maybe need to parse `NAMESPACE` -- shouldn't be too bad.

**Comment by MichaelChirico** [comment]
> I'm not sure if tests already see the new getNamespaceExports() when a new linter is added, but I'd say we should definitely add a test for that if we check this.

Can't see why not. tests are run after the package is built so the namespace seen by tests should be what we want.

**Review by AshesITR — APPROVED** [review]

**Pull request merged**
