### PR TITLE
use parameterized test on public API for implicit_integer_linter()

### PR DESCRIPTION
**Pull request by MichaelChirico**
Part of #1692

### CODE REVIEW

**Review by IndrajeetPatil — APPROVED** [review]
LGTM. Thanks!

Btw, why do you use `local()` with `{patrick}` tests? 
I didn't use it for the tests I wrote, and I can change that if I understand the reasoning here.

**Comment by MichaelChirico** [comment]
> Btw, why do you use local() with {patrick} tests?

because of the extra variables associated with the test (`cases`, `int_max`, `cases_int_max`)... those are needed for the test but make the tests less "hermetic" by polluting the local environment (can possibly be seen by other tests, by mistake). `local()` ensures those are removed "on.exit" from the `local()` execution frame.

There's another approach that could work with {rlang} but I prefer the `local()` one for now...

https://github.com/r-lib/withr/issues/205

**Comment by MichaelChirico** [comment]
(with plain {testthat} tests, this is encapsulated in `test_that()`, but we need this workaround for {patrick}... hmm maybe that could be improved upstream...)

**Comment by IndrajeetPatil** [comment]
> make the tests less "hermetic" by polluting the local environment (can possibly be seen by other tests, by mistake)

I see. Thanks for clarifying!

My understanding was that objects created in each test file live in their own local environments and won't be accessible from other test files. But maybe there are contexts (like `{patrick}` tests) where this is possible?

**Comment by MichaelChirico** [comment]
> My understanding was that objects created in each test file live in their own local environments

I think that's right, but there are also the other tests in the same file

PS filed: https://github.com/google/patrick/issues/13

**Pull request merged**
