### PR TITLE
DO NOT MERGE: Check lintr comment bot

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
#854

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@jimhester, @MichaelChirico Does this mean that lintr bot on GitHub no longer posts comments in the PR? 

P.S. Annotations work just fine. This question and experimental PR is inspired by #854.

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by MichaelChirico** [comment]
I never really knew how the bot worked, so i can't confirm or deny :)

**Comment by jimhester** [comment]
Likely the PAT got invalidated, which is why the bot is not working.

I guess there is some question as to whether we should just get rid of the commenting, as it is probably better to use annotations instead now that they exist.

**Comment by MichaelChirico** [comment]
Agree, the current status quo on this repo using annotations & failing the CI if lints are found works well for us. Let's recommend that instead.

**Comment by IndrajeetPatil** [comment]
I think this issue can also be closed for similar reasons? 
https://github.com/r-lib/lintr/issues/364

**Pull request closed without merging**
