### PR TITLE
Add blog post to the website

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Related to https://github.com/r-lib/lintr/issues/824

### CODE REVIEW

**Comment by MichaelChirico** [comment]
nice! any idea how we can preview this? does this override the automatic versioning inferred from NEWS.md?

**Comment by IndrajeetPatil** [comment]
> any idea how we can preview this?

Good question. I'm not sure.
@maelle Sorry to bother you. But, is there any way to preview pkgdown website built in the PR?

> does this override the automatic versioning inferred from NEWS.md?

No, it won't. The NEWS menu should look something like this (of course, there will just be a single entry for `3.0.0` release) after the PR is merged.

Screenshot 2022-07-25 at 10 24 27

**Comment by maelle** [comment]
- you could do like pkgdown's own repo https://github.com/r-lib/pkgdown/blob/main/.github/workflows/pkgdown.yaml#L59= using Netlify, or https://developers.cloudflare.com/pages/platform/preview-deployments/ that I was recently told about
- in cynkra/fledge if a branch name starts with docs it's deployed to the development website if I'm not mistaken see https://github.com/cynkra/fledge/blob/main/.github/workflows/pkgdown.yaml

**Review by MichaelChirico — APPROVED** [review]

**Comment by MichaelChirico** [comment]
Thanks!

**Pull request merged**
