### PR TITLE
Avoid paste0 overhead in is_lint_level

### LINKED ISSUE #2358: Speed up `is_lint_level()` by avoiding a `paste0()` call.
But it could be sped up by avoiding a `paste0()` call.

_Originally posted by @AshesITR in https://github.com/r-lib/lintr/pull/2352#discussion_r1405682606_

The function was called many times and is featured for creating linters as well.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #2358

### CODE REVIEW

**Review by AshesITR — CHANGES_REQUESTED** [review]
Can you benchmark `switch()` vs. `if()` first?

**Comment by IndrajeetPatil** [comment]
I had done a quick benchmarking locally that I am producing here, but not sure if you are actually looking for benchmark for `lint_package()` (e.g.) after this change. I didn't do the latter before approving.

``` r
level <- "expression"

bench::mark(
  "if" = paste0(if (level == "file") "full_", "parsed_content"),
  "switch" = switch(level,
    file = "full_parsed_content",
    expression = "parsed_content"
  ),
  iterations = 1000,
  time_unit = "us"
)
#> # A tibble: 2 × 6
#>   expression   min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <dbl>  <dbl>     <dbl> <bch:byt>    <dbl>
#> 1 if         0.902 0.984    881984.        0B        0
#> 2 switch     0     0.0410 21351784.        0B        0
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AshesITR** [comment]
I was thinking `if (level == "expression") "parsed_content" else "full_parsed_content"`, still without `paste0()`.

**Comment by IndrajeetPatil** [comment]
Ah, I see. Here it is:

``` r
level <- "expression"

bench::mark(
  "if" = if (level == "file")  "full_parsed_content" else "parsed_content",
  "switch" = switch(level,
                    file = "full_parsed_content",
                    expression = "parsed_content"
  ),
  iterations = 1000,
  time_unit = "us"
)
#> # A tibble: 2 × 6
#>   expression    min median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>  <dbl>  <dbl>     <dbl> <bch:byt>    <dbl>
#> 1 if         0.0410 0.0820  6850171.        0B        0
#> 2 switch     0      0.0410 19969240.        0B        0
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by AshesITR** [comment]
On a computer now, could check,'

``` r
level <- "expression"

bench::mark(
  "if" = if (level == "expression") "parsed_content" else "full_parsed_content",
  "switch" = switch(level,
    file = "full_parsed_content",
    expression = "parsed_content"
  )
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 if            120ns    128ns  6010347.        0B        0
#> 2 switch         76ns     83ns  9321876.        0B        0

level <- "file"

bench::mark(
  "if" = if (level == "expression") "parsed_content" else "full_parsed_content",
  "switch" = switch(level,
    file = "full_parsed_content",
    expression = "parsed_content"
  )
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 if          123.1ns  132.1ns  6368058.        0B        0
#> 2 switch       68.9ns   75.1ns 10365642.        0B        0
```

<sup>Created on 2023-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Review by AshesITR — APPROVED** [review]

**Comment by AshesITR** [comment]
Here are some larger benchmarks:

expression
```
# A tibble: 2 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec`   n_itr  n_gc total_time result    memory             time                    gc                       
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>   <int> <dbl>   <bch:tm> <list>    <list>             <list>                  <list>                   
1 if            115ns    129ns  6658306.        0B     17.3 9999974    26       1.5s <chr [1]> <Rprofmem [0 × 3]> <bench_tm [10,000,000]> <tibble [10,000,000 × 3]>
2 switch       70.9ns     80ns 10382848.        0B     26.0 9999975    25    963.1ms <chr [1]> <Rprofmem [0 × 3]> <bench_tm [10,000,000]> <tibble [10,000,000 × 3]>
```

file
```
# A tibble: 2 × 13
  expression      min   median `itr/sec` mem_alloc `gc/sec`   n_itr  n_gc total_time result    memory             time                    gc                       
  <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>   <int> <dbl>   <bch:tm> <list>    <list>             <list>                  <list>                   
1 if            118ns  134.1ns  6591956.        0B     16.5 9999975    25      1.52s <chr [1]> <Rprofmem [0 × 3]> <bench_tm [10,000,000]> <tibble [10,000,000 × 3]>
2 switch         63ns   70.1ns 11524237.        0B     28.8 9999975    25   867.73ms <chr [1]> <Rprofmem [0 × 3]> <bench_tm [10,000,000]> <tibble [10,000,000 × 3]>
```

**Pull request merged**
