### PR TITLE
Bump checkout action to the latest version

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by MichaelChirico** [comment]
It would be nice if there was a way to only have to update this once and have it cascade to all the actions in our repo, is that possible?

**Comment by IndrajeetPatil** [comment]
Not that I am aware of. But, TBH, we shouldn't be doing this manually anyway. And, once https://github.com/r-lib/lintr/pull/2120 is merged, we won't need to. This process will get automated.

**Comment by MichaelChirico** [comment]
> Not that I am aware of. But, TBH, we shouldn't be doing this manually anyway. And, once #2120 is merged, we won't need to. This process will get automated.

Thanks! I read this PR before #2120 🙈. As long as it's automated it will be fine -- I was more worried about "missing" one action by mistake if done manually.

**Review by MichaelChirico — APPROVED** [review]

**Comment by MichaelChirico** [comment]
Looks like #2121 will be ready to merge first & it's a wee bit nicer to have this generated automatically. Closing, but thanks!

**Pull request closed without merging**
