### PR TITLE
New for_loop_index_linter

### PR DESCRIPTION
**Pull request by MichaelChirico**
Part of #884 

This one is not violated often in our experience, but it's quite bad when it is.

```
x <- 1:10
for (x in x) x
x
# [1] 10
```

Seems like undesirable behavior.

### CODE REVIEW

**Review by IndrajeetPatil — DISMISSED** [review]
LGTM. 

The only nitpick I have is using `` `for()` `` instead of _for_ in the docs and message. But don't feel strongly about it.

**Comment by MichaelChirico** [comment]
"for loop" is a much more general programming construct, `for()` doesn't look right to me. I'll keep it as is. Thanks!

**Comment by IndrajeetPatil** [comment]
Sure, but I find it easier to parse the following 

> This is true for `for()` loops.

over this

> This is true for for loops.

**Review by IndrajeetPatil — APPROVED** [review]

**Comment by MichaelChirico** [comment]
Sure, I would disambiguate with "for `for` loops", but that's not used here anyway?

**Pull request merged**
