### PR TITLE
Sort default_undesirable docs robustly

### PR DESCRIPTION
**Pull request by MichaelChirico**
Have been getting some spurious diffs vs. `main` on this. Is anyone else seeing it? I'm a bit surprised because the `default*` objects are coming from `modify_defaults()`, which uses `platform_independent_order()` already:

https://github.com/r-lib/lintr/blob/fdbb9bfa1ea868ad66c6fe9a30b4ae872c03f56e/R/with.R#L59

Maybe this is a call to improve `platform_independent_order()`? That's pretty rudimentary indeed:

https://github.com/r-lib/lintr/blob/fdbb9bfa1ea868ad66c6fe9a30b4ae872c03f56e/R/utils.R#L206-L207

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
> Is anyone else seeing it?

Yes, indeed, I was seeing these diffs in this `.Rd` file while working on some other PRs.

**Comment by AshesITR** [comment]
Me too. I manually roll those changes back before committing. Similarly for some snapshot tests (Windows recreates them with CRLF endings on at least one of my machines)

**Comment by MichaelChirico** [comment]
OK, switched to using `LC_COLLATE` for full robustness.

Per https://github.com/r-lib/withr/issues/179, it's also possible to see some interference with `LC_COLLATE` envvar, but not adding that complication yet since this is only needed for dev.

**Comment by Bisaloo** [comment]
In case that's useful, `method = "radix"` will always use C locale for character strings. It can be a convenient way to get locale-independent sorting without directly tweaking the LOCALE settings

**Comment by IndrajeetPatil** [comment]
@Bisaloo This is great! 

## With the default sorting method

``` r
callr::r(
  function() withr::with_collate("C", sort(c("a", "_a", "A"))),
  env = c(LC_COLLATE = "C")
)
#> [1] "A"  "_a" "a"

callr::r(
  function() withr::with_collate("en_US", sort(c("a", "_a", "A"))),
  env = c(LC_COLLATE = "en_US")
)
#> [1] "_a" "a"  "A"
```

## With the radix sorting method

```r
callr::r(
  function() withr::with_collate("C", sort(c("a", "_a", "A"), method = "radix")),
  env = c(LC_COLLATE = "C")
)
#> [1] "A"  "_a" "a"

callr::r(
  function() withr::with_collate("en_US", sort(c("a", "_a", "A"), method = "radix")),
  env = c(LC_COLLATE = "en_US")
)
#> [1] "A"  "_a" "a"
```

<sup>Created on 2023-12-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichaelChirico** [comment]
> In case that's useful, `method = "radix"` will always use C locale for character strings. It can be a convenient way to get locale-independent sorting without directly tweaking the LOCALE settings

awesome idea! thank you {data.table} 😅

**Review by IndrajeetPatil — APPROVED** [review]

**Pull request merged**
