### PR TITLE
Check vigilant workflow when tests run in parallel

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@MichaelChirico, @AshesITR Do you know why `test_dir()` fails to run tests when the tests are run in parallel with "warnings-as-errors" setting turned on?

**Comment by AshesITR** [comment]
I have no idea. Seems to fail pretty early.
Maybe worth asking over at the testthat repo?

**Comment by IndrajeetPatil** [comment]
> Maybe worth asking over at the testthat repo?

I would do that if this is indeed a bug or something. But I am not sure if they tolerate me using the issue to ask for clarification, so prefer not to do that as yet.

**Comment by AshesITR** [comment]
Sure, but maybe trying to create a reprex helps find the issue anyway?

**Comment by IndrajeetPatil** [comment]
Closing in favour of #2297

**Pull request closed without merging**
