### PR TITLE
WIP: Remove deprecated workarounds

### LINKED ISSUE #1504: CRAN failures, new release requested by 2022-08-30
```
Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_lintr.html>.

Apparently your package fails its checks in a strict Latin-1* locale,
e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
results).

Please correct before 2022-08-30 to safely retain your package on CRAN.
```

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
These were slated for the next release after `3.0.0`.

So probably will be part of the release to be made for #1504?

### CODE REVIEW

**Comment by AshesITR** [comment]
I think this is a bit early for removing the aliases given that 3.0.1 is more of a maintenance release.

**Comment by IndrajeetPatil** [comment]
This is still WIP, and will be part of 3.1.0.

3.0.1 is already submitted to CRAN.

**Comment by MichaelChirico** [comment]
The real deprecation cycle we'll follow will be to upgrade `warning()` to `stop()` in `3.1.0`, and then remove the workaround later in `3.2.0`.

**Comment by IndrajeetPatil** [comment]
Okay, sounds good. I will change the milestone for this PR.

I or someone else can make a separate PR to turn these warnings into errors when we are ready for 3.1.0.

**Pull request closed without merging**
